[project]
name = "jdmgeneformer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "hyperopt>=0.2.7",
    "ray[default]>=2.48.0",
    "torch>=2.7.1",
    "transformers>=4.54.1",
    "numpy<=2.2",
    "ipykernel>=6.30.0",
    "path>=17.1.1",
    "wandb>=0.21.0",
]
